# Generated by Django 5.1.3 on 2024-11-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_food_restaurants_category_restaurants_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categoria',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('name',), 'verbose_name': 'Comida', 'verbose_name_plural': 'Comidas'},
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='category',
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='menu',
            field=models.ManyToManyField(related_name='restaurants', to='restaurants.food', verbose_name='Comida'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='category',
            field=models.ManyToManyField(related_name='restaurants', to='restaurants.category', verbose_name='Categoria'),
        ),
    ]
