# Generated by Django 5.1.3 on 2024-12-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurants_total_resevations'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
