# Generated by Django 5.1.3 on 2025-01-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurants_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='price_reservation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Reserva'),
        ),
    ]
