# Generated by Django 5.1.3 on 2025-01-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurants_price_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='price_reservation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Reserva'),
        ),
    ]
