# Generated by Django 5.1.3 on 2024-11-29 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='restaurante',
            new_name='restaurant',
        ),
    ]
